package navimateforbusiness

class LeadM {
    static mapWith = "mongo"

    // Auto generated by mongo driver
    String id
    Long oldId

    // External ID for uploading through external sources
    String extId

    // Account of lead
    Long accountId

    // Uploader of lead
    Long ownerId

    // Visibility of Lead
    navimateforbusiness.Visibility visibility

    // Remove Flag
    boolean isRemoved = false

    // Lead Name
    String name

    // Location
    double latitude
    double longitude
    String address

    // Template for uploading templated data
    Long templateId

    static constraints = {
        extId           nullable: true
        oldId           nullable: true
    }

    static mapping = {
        accountId index:true
        templateId index:true
    }
}
