package navimateforbusiness

class ProductM {
    static mapWith = "mongo"

    // Auto generated by mongo driver
    String id

    // Creation / Update time
    String dateCreated
    String lastUpdated

    // Account of Product
    Long accountId

    // Uploader of Product
    Long ownerId

    // Product ID
    String productId

    // Product Name
    String name

    // Template for uploading templated data
    Long templateId

    static mapping = {
        accountId index:true
        templateId index:true
        autoTimestamp false
    }
}
