---
grails:
    profile: web
    codegen:
        defaultPackage: navimateforbusiness
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    databinding:
        convertEmptyStringsToNull: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        maxFileSize: 2000000
        maxRequestSize: 2000000
        upload:
          maxFileSize: 2000000
          maxRequestSize: 2000000
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    plugin:
        databasemigration:
            updateOnStart: true
            updateOnStartFileNames:
                - changelog.groovy
        awssdk:
            region: us-west-2

endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver

environments:
    development:
        dataSource:
            url: jdbc:postgresql://localhost:5432/navimate
            username: navimate
            password: navimate
        grails:
            redis:
                timeout: 2000 # default in milliseconds
                port: 6379
                host: localhost
            mail:
              host: "smtp.gmail.com"
              port: 465
              username: "navm8dev@gmail.com"
              password: "navm8devpass"
              props:
                  mail.smtp.auth: "true"
                  mail.smtp.socketFactory.port: "465"
                  mail.smtp.socketFactory.class: "javax.net.ssl.SSLSocketFactory"
                  mail.smtp.socketFactory.fallback: "false"
            plugin:
                awssdk:
                    s3:
                        accessKey: "AKIAJBDGFQ5JNLKWPT6A"
                        secretKey: "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"
                        bucket: 'navimate-biz-dev'
    test:
        dataSource:
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            url: jdbc:postgresql://localhost:5432/navimate
            username: navimate
            password: "${NAVIMATE_DB_PASSWORD}"
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        grails:
            mail:
                host: "email-smtp.us-west-2.amazonaws.com"
                port: 587
                username: "${AWS_SES_ACCESS_KEY}"
                password: "${AWS_SES_SECRET_KEY}"
                from: "navimateapp@gmail.com"
                props:
                    mail.smtp.auth: "true"
                    mail.smtp.starttls.enable: "true"
                    mail.from: "navimateapp@gmail.com"
                javaMailProperties:
                    mail.smtp.auth: "true"
                    mail.smtp.starttls.enable: "true"
                    mail.from: "navimateapp@gmail.com"
            plugin:
                awssdk:
                    s3:
                        accessKey: "${AWS_S3_ACCESS_KEY}"
                        secretKey: "${AWS_S3_SECRET_KEY}"
                        bucket: 'navimate-biz-prod'
